language: node_js

node_js:
  - "stable"

branches:
  only:
    - latest

git:
  submodules: false
  depth: 1

install:
  - npm ci

script:
  - npm run  lint
  - npm test
  - npm run build

after_success:
  - npm run coverage
