version: "3"

services:
    node:
        container_name: node
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - .:/home/user/app

    npm:
        container_name: npm
        build:
            context: docker/npm
            dockerfile: Dockerfile
        volumes:
            - .:/home/user/app

    sh:
        container_name: npm
        build:
            context: docker/sh
            dockerfile: Dockerfile
        volumes:
            - .:/home/user/app
